### ISSUE TITLE
Any idea to prevent unnecessary browser refresh?

### ISSUE THREAD

**Issue by dehghani-mehdi** [RickStrahl/Westwind.AspnetCore.LiveReload#16]
Hi,

As `FileSystemWatcher`'s `Change` event fires on save and doesn't care about the content, the browser will reload even if the content of file doesn't actually changes. for example if I press `Ctrl + S` without any change, this trigger the change event.
Any idea to prevent unnecessary browser refresh?

Great component btw.

**Comment by RickStrahl** [comment]
Unfortunately no. The filewatcher doesn't seem to be able to watch only on file size changes, but triggers off the last write time.

> Any idea to prevent unnecessary browser refresh?

Don't make unnecessary save operations? :smile:

In all seriousness though - I think that's actually a useful feature as Ctrl-S allows you to refresh the view regardless of whether you made a change or not. It's a nice way to refresh browser content via a hot key essentially.

**Comment by dehghani-mehdi** [comment]
I usually hit `ctrl+s` multiple times, it is one of my _bad_ habits. (I can not fix this xD)

Webpack knows about my habit and refresh the browser only after real changes, _send change signal to browser though_. I don't know how Webpack handle that, maybe I should see its source code.

Thank you anyway.
