### ISSUE TITLE
Web page is not refreshing automatically

### ISSUE THREAD

**Issue by gang89** [RickStrahl/Westwind.AspnetCore.LiveReload#21]
Hi,

Thanks for this awesome library.

I added this library to my .net core 3.0 razor project (running on docker-compose). Have followed the instructions on setting up the live reloading.

One issue I am facing is that I have to manually refresh my webpage in order to see the razor page UI changes - instead of the web browser automatically refreshing upon saving the cshtml file.

Any advise on what might be causing this issue?

Thanks!

**Comment by RickStrahl** [comment]
You need to make sure you add:

```cs
services.AddRazorPages().AddRazorRuntimeCompilation();
services.AddMvc().AddRazorRuntimeCompilation();
```

along with the runtime compilation packages. See docs...

Without this 3.x projects will not recompile the pages.
