### ISSUE TITLE
Incorrectly refresh on "" extension value

### ISSUE THREAD

**Issue by dotlegacy** [RickStrahl/Westwind.AspnetCore.LiveReload#23]
Found a bug where it refreshes when the extension value of the file that was changed is "".  The ClientFileExtensions string should be parsed into a list to check for actually ext value.  Below is sample code that I used to fix it:
LiveReloadConfiguration.Current.ClientFileExtensions.Split(',', System.StringSplitOptions.RemoveEmptyEntries).ToList().Contains(ext)

Also, the icon.png is missing in the Westwind.AspnetCore.LiveReload and LiveReloadServer folder.

**Comment by RickStrahl** [comment]
Thanks. Updated. I actually had put in a null/empty check at some point so the underlying issue was fixed. However, using the code above is more reliable overall so updated to use it instead. Thank you.
