### ISSUE TITLE
Blazor 3.1 sample

### ISSUE THREAD

**Issue by mrjohnr** [RickStrahl/Westwind.AspnetCore.LiveReload#24]
Hi
Is there any Blazor 3.1 sample?
I've tried it no luck
I've added   also

```
 services.AddRazorPages().AddRazorRuntimeCompilation();
 services.AddMvc().AddRazorRuntimeCompilation();

``` 

I go into Server folder execute: ` dotnet watch run`
in Opera browser I navigate to `https://localhost:5001`
In Vs code I change  `Client\Pages\Counter.razor`,I can see in console the app recompiling but browser not refreshing
thanks for any help
I've post my sample project [here ](https://www37.zippyshare.com/v/cyVsK1GS/file.html)

**Comment by RickStrahl** [comment]
This project is not designed specifiaclly to work with Blazor. Please see the on Blazor in the README file.

**Comment by dotnetshadow** [comment]
@mrjohnr Did you manage to solve the issue? 

@RickStrahl 
I have a similar issue. Using blazor web assembly 3.2.0, followed the instructions in the README (LiveReload 0.2.4.2) but can't see the changes in the browser. 

The page reloads but nothing is updated. I'm guessing the dll isn't getting recompiled before it's refreshed?

```
"LiveReload": {
    "LiveReloadEnabled": true,
    "ClientFileExtensions": ".css,.js,.htm,.html,.ts,.razor,.cs",
    "FolderToMonitor": "~/..",
    "AdditionalMimeMappings": {
      ".dll": "application/octet-stream"
    },
    "FolderNotFoundFallbackPath": "/index.html"
  }
```

I know there is an auto-reload function with visual studio as outlined here, that seems to work:
https://devblogs.microsoft.com/aspnet/blazor-webassembly-3-2-0-preview-3-release-now-available/

Perhaps I'm misunderstanding how this works with blazor?
