### ISSUE TITLE
Ignoring ServerRefreshTimeout

### ISSUE THREAD

**Issue by mucalytic** [RickStrahl/Westwind.AspnetCore.LiveReload#25]
I've set the ServerRefreshTimeout to 10000 (I assume, 10 seconds) in Startup.cs and appsettings.json and the page still refreshes after 3 seconds. Often, my build takes more than that, so it fails to load the page and I have to refresh it manually, thus defeating the point.

**Comment by RickStrahl** [comment]
I think the refresh timeout is no longer used. The recommended way to do this is during startup to generate an HTML file into monitored tree somewhere. I have to check and see how that works exactly again.
