### ISSUE TITLE
Blazor project 

### ISSUE THREAD

**Issue by timeshift92** [RickStrahl/Westwind.AspnetCore.LiveReload#3]
Does this exclusion work with a blazor?

**Comment by RickStrahl** [comment]
Yes it should. Definitely for serverside blazor and for client side blazor if you host it on aspnetcore.

**Comment by RickStrahl** [comment]
Ok so i took a look and while you can get it the refresh to work, it looks like Blazor itself has no mechanism itself to auto-recompile on changes to Blazor files. You'd have to save your file and recompile and then it would auto refresh.

I can't find a decent answer of whether that's me doing something wrong or whether Blazor really can't self recompile views. If that's true that would make it a horrible client side technology.

**Comment by Swellenator** [comment]
@RickStrahl  I had to put this into the .csproj file for `dotnet watch run` to trigger for my blazor code:

` <ItemGroup>
  <Watch Include="**\*.cshtml;**\*.razor" />
    </ItemGroup>
`

**Comment by timeshift92** [comment]
thanks for the answer, yes, and I checked blazor now with this problem, but here bolero for f # compile view on the go

**Comment by RickStrahl** [comment]
I think what you need in a client blazor project is:

```xml
<ItemGroup> <Watch Include="..\BlazorClientProject\**\*.cshtml;**\*.razor" /> </ItemGroup>
```

to point at the client project from the Core project. This works for me but it's very slow as both the Blazor app and the Core project recompile which is a pretty bad client side experience.

**Comment by timeshift92** [comment]
Thanks for the answer, then I will wait for better times
but for now I'll take care of the dart
