### ISSUE TITLE
FileIncludeFilter does not have getter and setter

### ISSUE THREAD

**Issue by hadisonick** [RickStrahl/Westwind.AspnetCore.LiveReload#35]
Athough the filter is listed in LiveReloadConfiguration, it can't be accessed as a property in Startup as no getter and setter is set. 

public Func<string, bool> FileIncludeFilter= null;

**Comment by RickStrahl** [comment]
It should still work as a field:

```cs
services.AddLiveReload(opt =>
{
                    opt.FolderToMonitor = ServerConfig.WebRoot;
                    opt.LiveReloadEnabled = ServerConfig.UseLiveReload;

                    opt.FileIncludeFilter = (path) => true;  // this works
}
```

But yes that's an omission on my part it should be a property.
