### ISSUE TITLE
Core 2.1 bug: applicationLifetime not set

### ISSUE THREAD

**Issue by TMox** [RickStrahl/Westwind.AspnetCore.LiveReload#41]
Hey @RickStrahl, thanks for LiveReload!
I'm using it on an old Core 2.1 app (my host doesn't support 3.x!!), and I found an oversight in your code.
It's a one-line change, and if nobody has told you about it, it's probably insignificant, but if you want to fix it, or have me fix it, just add 
                applicationLifetime = lifeTime;
in LiveReloadMiddleware.cs line 45 (in the NETCORE2 case).
Thanks.

**Comment by RickStrahl** [comment]
Thanks. Fixed for next updated.
