### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by GravlLift** [RickStrahl/Westwind.AspnetCore.LiveReload#44]
Looks like the nuget package has updated to 0.3.0 as of about two weeks ago, but there's no corresponding code update on this repo. What changes are contained in v0.3.0?

**Comment by RickStrahl** [comment]
v3.0 was for the .NET 5.0 updates and removal of support for .NET Core 2.x.

Checking. Oh crap - yeah those changes weren't merged into Master. Doing that now. Thanks.
