### ISSUE TITLE
Firefox - Strange issue not refreshing the correct route

### ISSUE THREAD

**Issue by dotnetshadow** [RickStrahl/Westwind.AspnetCore.LiveReload#45]
Hi Rick,

I seem to have a strange issue with Firefox on a particular route it's not reloading the page correctly.
If I try it in Edge and Chrome then it seems to work properly.
I downloaded a portable version of Firefox to make sure it wasn't something with my Firefox profile and the same issue happened

Basically my route involves have a slug in the url `games/my-game/dashboard`. But for some reason the livereload request seems to go to `games` route.

It's hard to demonstrate this without seeing the code,  Basically if I go to the request the very first time it works, but as livereload kicks in the next request is incorrect. 

If I open the page in another tab that page works correctly, but if I try to navigate to another section it stops working. If I open that section in another tab that works but again the same issue exists can't navigate within that section. It keeps reloading the same page

I can see that the it actually navigates to the correct route, but then livereload causes the next get request to use the route before the one I'm requesting.
If I disable livereload then everything works as normal.

I was wondering is there anyway to setup a remote session or something so you could possibly see and debug the error?

**UPDATE**
I think I found the issue, the page was taking longer to return for one particular route. So I think livereload kicks in before the request had a chance to return the results. I can see though the log the correct page was being hit, but it hadn't pushed down to the browser yet. 

In the meant time livereload was requesting the page for any changes so it must of been using the current url as opposed to the one that should be returning from the server. I guess it was a timing issue.

As a sidenote it helped me work out I had a slow running query :)

**Comment by RickStrahl** [comment]
There's a timeout option in the configuration that lets you tweak a delay between the changed file and the refresh firing. Perhaps you can increase that timeout. Problem is for anything more than a few seconds this becomes problematic as it slows everyting down.

There's also an option to look at specific page requests and customize what happens or whether it should refresh at all. If you know you have a slow request you can write a handler that delays execution for just that one request.

**Comment by alirezaja1384** [comment]
> There's a timeout option in the configuration that lets you tweak a delay between the changed file and the refresh firing. Perhaps you can increase that timeout. Problem is for anything more than a few seconds this becomes problematic as it slows everyting down.

Thanks a lot, changing timeout fixed the problem for me.
