### ISSUE TITLE
v0.3.1 - Firefox not working properly

### ISSUE THREAD

**Issue by dotnetshadow** [RickStrahl/Westwind.AspnetCore.LiveReload#48]
Hi Rick,

I just updated to **v0.3.1**   of your library, I noticed that in firefox my application is behaving a little odd.
I'm just navigating around my site without touching any files, but for some reason if I try to login into my app it just refreshes back to login screen. When I turn off livereload or revert to**v0.2.14**  there is no problem.

**Browsers Tested**
I even downloaded a portable version of Firefox but it still had the issue 
https://portableapps.com/apps/internet/firefox_portable

Chrome or Edge seem to be fine.

So not sure what the possible cause could be with v0.3.1 and Firefox.
Please note it doesn't happen on all pages, but so far I can't login into my site without it being affected

**Attempt**
The next thing I tried was to create a new asp.net core (MVC) project. I tried to register a user using Firefox, but upon submit the page just refreshed back to itself. Ideally it should of taken me toe the "Enable Migrations" page that usually comes up on the very first attempt. When I tried the same thing in Chrome it worked.

I was able to login using Firefox, but if I went ahead and changed the `Home/Index.cshtml`, no changes would be shown in Firefox, but Chrome showed the changes. I had to go back to **v0.2.14**  for it to update correctly in Firefox. 

**Demonstration (GIF)**
The strange thing is that I can see that Firefox is trying to refresh because the tab shows an indicator.
What's more interesting is the following: 
If I change some text "Welcome" to "Welcome1" - no visible change in firefox
If I make a further edit and change "Welcome1" to "Welcome2" - Firefox shows "Welcome 1", somehow it's one edit behind
If I make a further edit change "Welcome2" to "Welcome3" - Firefox keeps showing "Welcome2" so it doesn't always update correctly.

_Please note the top browser is Firefox and the bottom browser is Chrome_

![firefox](https://user-images.githubusercontent.com/296247/104462914-3e00d800-5605-11eb-824a-612da3bba307.gif)

**Test Project**
I've added a test project (asp.net core 5,0) so that you can try it in firefox so you can test whether you are seeing the same issue
[WebApplicationLiveReload.zip](https://github.com/RickStrahl/Westwind.AspnetCore.LiveReload/files/5808959/WebApplicationLiveReload.zip)

**Similar Issue**
I did raise something similar before, so I'm not sure if it's related to changes made in **v0.3** or if this has been an issue for a while
I just tried **v0.2.14** that too sometimes fails in Firefox
#45 

### UPDATE
After further testing on Firefox:

- [x] Verified that  **v0.3.0** and **v0.3.1** refreshes the page when edits are made - WORKING
- [x]   **v0.3.0** can login properly - WORKING
- [ ]  **v0.3.0**  needs ServerRefreshTimeout increased for some pages while navigating around the site (3-5 seconds) 
- [ ]  **v0.3.1**  doesn't allow me to login - NOT WORKING

Happy to have a teamviewer session to show the issue if that helps out

**Comment by dotnetshadow** [comment]
Firefox Thought the issue was fixed but I had occidentally disabled LiveReload

**Comment by dotnetshadow** [comment]
This issue can be closed, it seems to be working now

**Comment by g0tsimid** [comment]
This is due to the onclose handler causing the page to reload and interrupt the original navigation process. I was able to find a workaround by creating a custom livereload.js that listens to the beforeunload event and bypasses the onclose logic:

```js
    var isClosing = false;
    window.addEventListener("beforeunload", function () {
        // Prevent reload events triggered by closing the connection from interrupting navigation.
        isClosing = true;
        console.debug("Live Reload is paused due to beforeunload event.");
        setTimeout(function () {
            // Assume that the user clicked Stay on Page if this logic is executing after the timeout.
            isClosing = false;
            if (connection) {
                connection.onopen = null;
                connection = tryConnect(true);
                console.debug("Live Reload has resumed after unload was cancelled.");
            }
        }, 2500);
    });
    var connection = tryConnect(true);

    function tryConnect(retryOnFail) {
...
        connection.onclose = function (event) {
            console.log('Live Reload Socket closed.');
            if (retryOnFail && !isClosing)
                retryConnection();
        }
```

This also requires setting the `LiveReloadScriptUrl` option to point to this file, and changing the middleware order so that `UseStaticFiles` is above `UseLiveReload`.

I'd like to submit a PR merging these changes into the main __livereloadscript endpoint, if that's alright.

**Comment by dotnetshadow** [comment]
@g0tsimid Thank you so much for looking into it, sounds like you were able to identify the issue and have a fix for it, well done

**Comment by dotnetshadow** [comment]
@RickStrahl Hi Rick, was wondering if you would have a chance to merge the pull request?
