### ISSUE TITLE
Have "FolderToMonitor" accepts an array to monitor multiple locations

### ISSUE THREAD

**Issue by DamienLaw** [RickStrahl/Westwind.AspnetCore.LiveReload#50]
I came across a need to be able to monitor files changes in multiple locations. If only `FolderToMonitor` could accept an array of strings (probably rename it to `FoldersToMonitor` while we're at it).

I know I could use the delegate `FileInclusionFilter` to filter the paths that I want monitored, but I'd rather save time from coding trivial functionality like this since the existing feature is already half way there.

I could submit a pull request expanding on `FolderToMonitor` if you're okay with it.

**Comment by RickStrahl** [comment]
What's the use case?

Seems to me you can always expand the scope of the root folder if necessary.
