### ISSUE TITLE
F# example of using this library

### ISSUE THREAD

**Issue by srid** [RickStrahl/Westwind.AspnetCore.LiveReload#51]
FYI,

https://github.com/srid/Feather/blob/master/src/Feather.Build/Library.fs#L17-L55

It takes a `IFileProvider` (`PhysicalFileProvider` only because I needed the root path, and that is because for some reason this library is not using asp.net's webroot configured using `UseWebRoot`) as an argument.

**Comment by RickStrahl** [comment]
Not sure I understand what you're asking. UseWebRoot() is an application wide setting that gets configured during startup. This component merely uses the Webroot provided.
