### ISSUE TITLE
Pairing with npm watch & vue

### ISSUE THREAD

**Issue by jakenuts** [RickStrahl/Westwind.AspnetCore.LiveReload#52]
Thanks so much for this great code - it's awesome. I'm hoping to get dotnet watch & npm watch lined up so that changes in either c# or vue files trigger build/reload and I'm close but the timing is a tiny bit off (vue changes show up one reload behind). Have you tried doing something similar?

**Comment by RickStrahl** [comment]
No, but you should be able to perhaps use custom filters to determine if a page is a vue page, and if so don't set live reload to that page. You can use the file filters (if it's an extension) or if that doesn't work use the explicit filter expression code delegates.
