### ISSUE TITLE
Overcoming the 5000 rules CSS limit

### ISSUE THREAD

**Issue by thepra** [RickStrahl/Westwind.AspnetCore.LiveReload#59]
I have this limitation:

>CSS Hot Reload ignoring https://localhost:44335/css/style.css because it was inaccessible or had more than 5000 rules.

Is there a way to override this limit?

**Comment by RickStrahl** [comment]
I have no idea what you're talking about. What does this have to do with the server?

**Comment by thepra** [comment]
so it's not a message coming from LiveReload?

**Comment by RickStrahl** [comment]
This sounds like a browser issue - too many styles that the browser can't handle. Definitely not a server side message as the server just serves text.
