### ISSUE TITLE
Truncated responses?

### ISSUE THREAD

**Issue by pm64** [RickStrahl/Westwind.AspnetCore.LiveReload#9]
In general, LiveReload is phenomenal. But I'm seeing that in some cases, having LiveReload in the pipeline causes responses to get truncated, breaking the client. In these cases, the response is truncated even when LiveReloadEnabled=false. Removing LiveReload from the pipeline resolves the issue. Can this behavior be accounted for?

**Comment by RickStrahl** [comment]
Can you tell **what** fails exactly?

This was a big problem in the intial release but was updated more recently with a fix that re-writes the content length explicitly based on the actual size of the content. 

I suspect what's happening is that somehow the content-length and the actual content size is not matching up. It would be good have an example of what fails to take a look at the exact respsonse that's getting returned/truncated.

Let me know if you can produce a repro sample.

**Comment by pm64** [comment]
@RickStrahl - That explanation certainly sounds plausible, I'll do my best to get you a repro. I'm having difficulty pinpointing the issue but will continue investigating.

**Comment by RickStrahl** [comment]
Closing since we haven't heard back - feel free to reopen if you find a repro scenario that I can try.

**Comment by samueldjack** [comment]
I've just encountered the problem of truncated responses with version 0.1.5.2. 

It only happens when I run the project from Visual Studio using the In-Process hosting model. If I switch to Out of Process nothing gets truncated, likewise using "dotnet watch run"
